### ISSUE TITLE
Is it working with openwakeword pipeline form homeassistant

### ISSUE THREAD

**Issue by rvsh2** [tetele/onju-voice-satellite#31]
Hi,

Please let me know is it working with openwakeword in assist pipeline in home assistant or only with microwakeword ?

Thanks.

**Comment by tetele** [comment]
There are 2 configs:
- [one for openWakeWord](https://github.com/tetele/onju-voice-satellite/blob/main/esphome/onju-voice.yaml)
- [one for microWakeWord](https://github.com/tetele/onju-voice-satellite/blob/main/esphome/onju-voice-microwakeword.yaml), which is experimental and has some limitations due to missing functionality in ESPHome
